src/Entity/Children.php
<?php

namespace App\Entity;

use App\Repository\ChildrenRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ChildrenRepository::class)
 */
class Children
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $nameChild;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $Teacher;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $nameTeacher;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $firstNameTeacher;

    public function getId(): ?int
    {
        return $this->id;
    }


    public function getNameChild(): ?string
    {
        return $this->nameChild;
    }

    public function setNameChild(string $nameChild): self
    {
        $this->nameChild = $nameChild;

        return $this;
    }

    public function getTeacher(): ?string
    {
        return $this->Teacher;
    }

    public function setTeacher(string $Teacher): self
    {
        $this->Teacher = $Teacher;

        return $this;
    }

    public function getNameTeacher(): ?string
    {
        return $this->nameTeacher;
    }

    public function setNameTeacher(string $nameTeacher): self
    {
        $this->nameTeacher = $nameTeacher;

        return $this;
    }

    public function getFirstNameTeacher(): ?string
    {
        return $this->firstNameTeacher;
    }

    public function setFirstNameTeacher(string $firstNameTeacher): self
    {
        $this->firstNameTeacher = $firstNameTeacher;

        return $this;
    }
}

templates/fragments/chat_frame.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <title>BotMan Widget</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/botman-web-widget@0/build/assets/css/chat.min.css">
</head>
<body>

<script id="botmanWidget" src='https://cdn.jsdelivr.net/npm/botman-web-widget@0/build/js/chat.js'></script>
</body>
</html>

templates/fragments/footer.html.twig
<footer class="bg-dark text-center text-white">
    <div class="container p-1 pb-0">
        <section class="mb-1">

            <a class="btn btn-outline-light btn-floating m-1" href="{{ path('information') }}" role="button">
                <i class="fas fa-user-tie fa-lg"></i> <br> Qui sommes-nous ?
            </a>


            <a class="btn btn-outline-light btn-floating m-1" href="{{ path('aide') }}" role="button">
                <i class="fas fa-question-circle fa-lg"></i><br>Besoin d'aide ?
            </a>


            <a target="blank" class="btn btn-outline-light btn-floating m-1" href="https://github.com/Richard-Nkr/DixFi-Thymio" role="button">
                <i class="fab fa-github fa-lg"></i> <br>Projet Github
            </a>
        </section>
    </div>
    <div class="text-center p-2">
        © 2021 Copyright -
        <a class="text-white" href="{{ path('home') }}"> Les Dix'Fi de Thymio</a>
    </div>
</footer>

templates/fragments/navbar.html.twig
<nav class="menu" id="menu_navbar">
    <ol>
        <li class="menu-item">
            <a href="{{ path('home') }}" class="home">
                <i class="fas fa-home"></i>
                <span>Les Dix'Fi de Thymio</span>
            </a>
        </li>

        <li class="menu-item">
            <a href="{{ path('youtube_index') }}" class="information">
                <i class="fas fa-info"></i>
                <span>Thymio c'est quoi ?</span>
            </a>
        </li>

        <li class="menu-item">
            <a href="#0" class="widgets">
                <i class="fas fa-trophy"></i>
                <span>Les Dix'Fi</span>
            </a>
            <ol class="sub-menu">
                {% if is_granted('ROLE_TEACHER') %}
                {% if app.user.progression == true %}
                    <li class="menu-item item--a"><a href="{{ path('thymio_challenge_desactivate_deblocage') }}"
                                                     class="item--a"><span>Desactivation du déblocage </span></a></li>

                {% else %}
                    <li class="menu-item item--a"><a href="{{ path('thymio_challenge_activate_deblocage') }}"
                                                     class="item--a"><span>Activation du déblocage </span></a></li>
                {% endif %}
                {% endif %}
                {% if is_granted('ROLE_STUDENT_GROUP') and app.user.teacher.progression==true %}
                    {{ render(controller('App\\Controller\\StudentGroupController::blockLevels') ) }}
                {% else %}
                <li class="menu-item item--a"><a href="{{ path('thymio_challenge_index', {'difficulty' : 'easy'}) }}"
                                                 class="item--a"><span>Dix'Fi Facile</span></a></li>
                <li class="menu-item item--a"><a href="{{ path('thymio_challenge_index', {'difficulty' : 'medium'}) }}"
                                                 class="item--a"><span>Dix'Fi Moyen</span></a></li>
                <li class="menu-item item--a"><a href="{{ path('thymio_challenge_index', {'difficulty' : 'hard'}) }}"
                                                 class="item--a"><span>Dix'Fi Difficile</span></a></li>
                <li class="menu-item item--a"><a href="{{ path('thymio_challenge_index', {'difficulty' : 'extreme'}) }}"
                                                 class="item--a"><span>Dix'Fi Extrême</span></a></li>
                {% endif %}
            </ol>
        </li>
        <li class="menu-item">
            <a href="#0" class="widgets">
                <i class="fas fa-pen"></i>
                <span>Teachers'Fi</span>
            </a>
            <ol class="sub-menu">
                <li class="menu-item"><a class="dropdown-item" href="{{ path('public_challenge_index') }}"><span>Les défis publics</span></a>
                </li>
                {% if is_granted('ROLE_STUDENT_GROUP') %}
                    <li class="menu-item"><a class="dropdown-item" href="{{ path('private_challenge_index') }}"><span>Les défis de mon professeur</span></a>
                    </li>
                {% endif %}
                {% if is_granted('ROLE_TEACHER') %}
                    <li class="menu-item"><a class="dropdown-item"
                                             href="{{ path('challenge_new') }}"><span>Créer un défi</span></a>
                    </li>
                    <li class="menu-item"><a class="dropdown-item" href="{{ path('challenge_show_my_challenge') }}"><span>Voir mes défis </span></a>
                    </li>
                {% endif %}
            </ol>

        </li>
        {% if is_granted('ROLE_TEACHER') %}
            <li class="menu-item">
                <a href="#0" class="kabobs">
                    <i class="fas fa-chalkboard-teacher"></i>
                    <span>Mon espace Teacher</span>
                </a>

                <ol class="sub-menu">
                    <li class="menu-item"><a href="{{ path('list_groups_to_validate') }}" class="item--a"><span>Validation des groupes</span></a>
                    </li>
                    <li class="menu-item"><a href="{{ path('list_groups_progress') }}"
                                             class="item--b"><span> Progression de mes groupes</span></a></li>
                    <li class="menu-item"><a href="{{ path('teacher_show') }}"
                                             class="item--b"><span> Mon profil</span></a></li>
                </ol>
            </li>

        {% else %}
            <li class="menu-item">
                <a href="#0" class="kabobs">
                    <i class="fas fa-lock"></i>
                    <span>Espace privé Teachers</span>
                </a>
            </li>
        {% endif %}

        <li class="menu-item">
            <a href="{{ path('user_index') }}" class="contact">
                <i class="fas fa-user-alt"></i>
                <span>Mon Profil</span>
            </a>
        </li>
    </ol>
</nav>